spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.125.128:3310/gulimall_pms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xmly
  global-config:
    db-config:
      id-type: auto
server:
  port: 10000